# -*- coding: utf-8 -*-
"""sprint1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DKCx5mxAFZ9DQyt6eo_ShzVPRz1Oh6oo
"""

pip install cv2

pip install opencv-python

pip install mediapipe

pip install cvzone

import cv2
from cvzone.HandTrackingModule import HandDetector

def detect(img):
    detector = HandDetector(maxHands=1, detectionCon=0.8)

    hand = detector.findHands(img, draw=False)

    if hand:
        lmlist = hand[0]
        if lmlist:
            fingerup = detector.fingersUp(lmlist)
            if fingerup == [0, 0, 0, 0, 0]: #No fingers are raised
                print('zero')
            if fingerup == [0, 1, 0, 0, 0]:#one finger is raised
                print('one')
            if fingerup == [0, 1, 1, 0, 0]: #two fingers are raised
                print('two')
            if fingerup == [0, 1, 1, 1, 0]: #three fingers are raised
                print('three')
            if fingerup == [0, 1, 1, 1, 1]: #Four fingers are raised
                print('four')
            if fingerup == [1, 1, 1, 1, 1]: #five fingers are raised
                print('five')
            if fingerup == [0,1,0,0,1]: #index and little fingers are raised
                print('success!!!')

from google.colab.patches import cv2_imshow


import matplotlib.pyplot as plt
img = cv2.imread(r"/content/drive/MyDrive/Sprint 1/Data/five.jpg") #reading image

plt.imshow(img)

img = cv2.imread(r"/content/drive/MyDrive/Sprint 1/Data/one.jpg") #reading image
plt.imshow(img)

img = cv2.imread(r"/content/drive/MyDrive/Sprint 1/Data/zero.jpg") #reading image
plt.imshow(img)

img = cv2.imread(r"/content/drive/MyDrive/Sprint 1/Data/close.jpg") #reading image
plt.imshow(img)

detect(img)